name: Generate MCQs with Free Ollama on GitHub

on:
  workflow_dispatch:
    inputs:
      content:
        description: 'Text content to generate MCQs from'
        required: true
        type: string
      difficulty:
        description: 'Difficulty level'
        required: false
        default: 'medium'
        type: choice
        options:
        - easy
        - medium
        - hard
      num_questions:
        description: 'Number of MCQs to generate'
        required: false
        default: '5'
        type: string

jobs:
  generate-mcqs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.ai/install.sh | sh
        ollama serve &
        sleep 15
        ollama pull llama2

    - name: Create content file
      run: |
        echo "${{ github.event.inputs.content }}" > content.txt
        echo "Content file created successfully"

    - name: Verify content
      run: |
        if [ ! -s "content.txt" ]; then
          echo "Error: No content provided"
          exit 1
        fi
        echo "Content verification successful. Content length: $(wc -c < content.txt) characters"

    - name: Generate MCQs with Ollama
      run: |
        # Create prompt with content
        cat > prompt.txt << EOF
        Generate ${{ github.event.inputs.num_questions }} multiple choice questions from the following text.
        Difficulty level: ${{ github.event.inputs.difficulty }}
        
        Text content:
        $(cat content.txt)
        
        Format each question as JSON with this structure:
        {
          "question": "Question text here?",
          "options": ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
          "correct_answer": "A",
          "explanation": "Brief explanation of why this is correct"
        }
        
        Return only valid JSON array format.
        EOF
        
        # Run Ollama and capture output
        echo "Running Ollama to generate MCQs..."
        ollama run llama2 < prompt.txt > mcq_output.json 2> ollama_error.log
        
        # Check if Ollama succeeded
        if [ $? -ne 0 ]; then
          echo "Ollama failed. Error log:"
          cat ollama_error.log
          exit 1
        fi
        
        # Verify output
        if [ ! -s "mcq_output.json" ]; then
          echo "Error: No output generated by Ollama"
          exit 1
        fi
        
        echo "MCQ generation completed successfully"

    - name: Validate JSON output
      run: |
        python3 -c "
        import json
        import sys
        
        try:
            with open('mcq_output.json', 'r') as f:
                data = json.load(f)
            
            if not isinstance(data, list):
                print('Error: Output is not a JSON array')
                sys.exit(1)
            
            for i, item in enumerate(data):
                required_fields = ['question', 'options', 'correct_answer', 'explanation']
                for field in required_fields:
                    if field not in item:
                        print(f'Error: Question {i+1} missing field: {field}')
                        sys.exit(1)
            
            print(f'JSON validation successful. Generated {len(data)} questions.')
            
        except json.JSONDecodeError as e:
            print(f'Error: Invalid JSON format - {e}')
            sys.exit(1)
        except Exception as e:
            print(f'Error: {e}')
            sys.exit(1)
        "

    - name: Generate HTML output
      run: |
        python3 scripts/generate_html.py "content.txt" "${{ github.event.inputs.difficulty }}" "${{ github.event.inputs.num_questions }}"

    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add generated files
        git add mcq_output.json
        git add content.txt
        git add "results/mcqs_content.txt.html"
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Generated MCQs from content (Difficulty: ${{ github.event.inputs.difficulty }}, Questions: ${{ github.event.inputs.num_questions }})"
          git push
          echo "Results committed and pushed successfully"
        fi

    - name: Cleanup temporary files
      if: always()
      run: |
        rm -f prompt.txt ollama_error.log content.txt